spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 10086
  main:
    banner-mode: off  #关掉控制台spring logo打印

#开启mp日志（输出到控制台）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false  #关掉控制台mp logo打印
    db-config:
      id-type: assign_id  #雪花算法生成id
      logic-delete-field: deleted   #逻辑删除字段
      logic-not-delete-value: 0
      logic-delete-value: 1
#     table-prefix: tbl_ 类名前面拼上tbl_